### ISSUE TITLE
"content" should not be configured as PropTypes.EmberObject.isRequired

### ISSUE THREAD

**Issue by notmessenger** [ciena-frost/ember-frost-object-browser#108]
The `content` property is used in the _/addon/templates/components/frost-object-browser.hbs_ file as `{{component content}}` which means that it's a component and applications specify it such as 

```
  {{frost-object-browser
    hook='network-constructs'
    content=(component 'frost-list'
      expandedItems=expandedItems
      hook='network-constructs'
      item=(component 'network-elements/list-item')
      itemExpansion=(component 'network-elements/list-item-expansion')
      items=items
      onExpansionChange=(action 'onExpansionChange')
      onLoadNext=(action 'onLoadNext')
      onSelectionChange=(action 'onSelectionChange')
      selectedItems=selectedItems
    )
```

once again making it a component, rather than an object.

When not specified correctly, and used as presented, this warning is displayed the the developer:

` Expected property content to be an Ember.Object`

**Comment by rox163** [comment]
Fixed in https://github.com/ciena-frost/ember-frost-object-browser/pull/112
