### ISSUE TITLE
"filters" should not be configured as PropTypes.EmberObject.isRequired

### ISSUE THREAD

**Issue by notmessenger** [ciena-frost/ember-frost-object-browser#110]
The `filters` property is used in the _/addon/templates/components/frost-object-browser.hbs_ file as `{{component filters}}` which means that it's a component and applications specify it such as 

```
  {{frost-object-browser
    filters=(component 'frost-bunsen-form'
      autofocus=false
      bunsenModel=filterModel
      bunsenView=filterView
      onChange=(action 'onFilteringChange')
      value=filters
    )
```

once again making it a component, rather than an object.

When not specified correctly, and used as presented, this warning is displayed the the developer:

` Expected property filters to be an Ember.Object`

**Comment by sglanzer** [comment]
Agreed, `EmberComponent` from PropTypes was giving linting issues at the time, but is the correct choice here
