### ISSUE TITLE
Add support for a loading animation in the action bar

### ISSUE THREAD

**Issue by jscharf** [ciena-frost/ember-frost-object-browser#144]
At Ciena we have a requirement for the action bar to display a loading animation, according to the UX specifications. This is to replace the current technique, which is to show a loading animation superimposed onto the button if that button requires time consuming logic to determine its state (for example, to determine if it should be disabled or not).

**Comment by juwara0** [comment]
Can you ping me privately with link to where this is discussed in the UX specifications please. I went looking but could not find anything. What I found was this sentence `There will not be any progress indicator for the loading of the actions on the action bar.`

**Comment by jscharf** [comment]
Sure I can send you a link to where some of this discussion was captured. I'm lowering the priority on this from high to medium, as this is not needed as quickly as we previously thought.
