### ISSUE TITLE
Replace deprecated perfect-scrollbar Bower dependency with updated NPM one

### ISSUE THREAD

**Issue by notmessenger** [ciena-frost/ember-frost-object-browser#148]
The Bower package https://github.com/utatti/perfect-scrollbar-bower has been deprecated in favor of an updated NPM one - https://github.com/utatti/perfect-scrollbar

**Comment by notmessenger** [comment]
JIRA: FROST-534

**Comment by notmessenger** [comment]
Will be evaluated in #149

**Comment by juwara0** [comment]
This was addressed in PR: https://github.com/ciena-frost/ember-frost-object-browser/pull/171. The `perfect-scrollbar` package is now being provided by `frost-scroll` inside `ember-frost-core` and so no longer needs to be provided by this add-on.
