### ISSUE TITLE
Address dependency management issues

### ISSUE THREAD

**Issue by notmessenger** [ciena-frost/ember-frost-object-browser#149]
https://github.com/ciena-frost/ember-frost-list/issues/167 **MUST** be resolved before this issue can be addressed.  Some of the individual tasks _may_ be able to be worked on before the completion of the dependent issue.  If doing so indicate which tasks have been completed by checking them off in the list below, as well as adding a comment to this issue indicating the name of the branch you have pushed to this repo so that work can completed once the dependent task has been addressed.

* Tasks that have the text _"(verified)"_ after them are ones that have either already been tested or are known to work.  This does not mean that you should not still be cautious but you likely don't have to do as much research as you might initially be inclinded to.
* None of the tasks make a determination of whether a dependency should be a **dependency** or **devDependency** _UNLESS_ otherwise stated.  Even then it is prudent to confirm this indicator.
* All dependencies should float to `^` unless the directions in the tasks indicate otherwise. The following entries are known items that should REMAIN pinned:
  * `ember-async-image`
  * `ember-cli-autoprefixer`
  * `ember-run-raf`

**NPM**

* [x] determine if ember-cli-sri is being used.  if not remove it.  if so ^2.1.1 is latest
* [x] change smoke-and-mirrors to github:ciena-frost/smoke-and-mirrors (verified)
* [x] remove ember-cli-import-polyfill (verified)
* [x] determine whether ember-async-image is needed
* [x] determine whether ember-browserify is needed.  if so ^1.2.0 is latest
* [x] upgrade ember-ajax to ^2.5.6 (verified)
* [x] `npm uninstall ember-frost-test` and `ember install ember-frost-test` (verified)
  * [x] `ember-cli-chai` will be updated to `0.4.3` so _may_ encounter issues
  * [x] `ember-cli-mocha` will be updated to `0.14.4` so _may_ encounter issues
  * [x] `ember-sinon` will be updated to `^0.7.0` so _may_ encounter issues
  * [x] `ember-test-utils` will be updated to `^7.02` so **will** encounter issues
* [x] remove ember-cli-moment-shim
* [x] pin ember-cli-code-coverage to 0.3.12
* [x] verify ember-cli-code-coverage is tied into "npm run test" script
* [x] keep `ember-code-snippet` at current version
* [x] pin ember-computed-decorators to 0.3.0 (verified)
* [x] upgrade ember-cli-sass to pinned 7.1.1 (verified)
* [x] update ember-hook to 1.4.2
* [x] determine whether ember-hook needs to be a **dependency**
* [x] pin ember-concurrency to 0.7.19 (verified)
* [x] upgrade ember-sortable to ^1.10.0
* [x] upgrade ember-math-helpers to pinned 2.0.6
* [x] remove ember-one-way-controls
* [x] update or install ember-cli-frost-blueprints to ^5.0.0 (or whatever the latest release is) as **devDependency**
* [x] remove from blueprints and make **dependency**
  * [x] ember-frost-core
  * [x] ember-frost-list
* [x] remove from devDependency and make **dependency**
  * [x] ember-frost-bunsen
  * [x] ember-frost-fields
  * [x] ember-frost-info-bar
  * [x] ember-frost-list
  * [x] ember-frost-popover
  * [x] ember-frost-sort
  * [x] ember-frost-tabs
  * [x] ember-prop-types
  * [x] ember-spread
* [x] delete blueprint
* [x] update ember-frost-bunsen to latest version
* [x] update ember-frost-fields to latest version
* [x] update ember-frost-info-bar to latest version
* [x] update ember-frost-list to latest version
* [x] update ember-frost-popover to latest version
* [x] update ember-frost-sort to latest version
* [x] update ember-frost-tabs to latest version
* [x] update ember-prop-types to ^6.0.0 (or whatever the latest release is)
* [x] update ember-spread to ^4.0.0 (or whatever the latest release is)
* [x] update ember-frost-core to ^5.0.0 (or whatever the latest release is)
* [x] determine **dependencies** vs **devDependencies**
* [x] check whether these are specifically needed or not and remove if not, otherwise move to dependencies
  * [x] ember-computed-decorators
  * [x] ember-concurrency
  * [x] ember-elsewhere
  * [x] ember-truth-helpers
* [x] remove `useLintTree` from `ember-cli-mocha` configuration in _ember-cli-build.js_

**BOWER**
* [x] remove jquery
* [x] move Faker to **devDependencies** of _bower.json_
* [x] move pretender to **devDependencies** of _bower.json_

perfect-scrollbar
* [x] remove entry for perfect-scrollbar in _bower.json_
* [x] npm install perfect-scrollbar@0.8.1
* [x] make perfect-scrollbar a **dependency** in _package.json_
* [ ] addresses #148
* [x] determine whether `jquery` is needed
* [x] determine whether `jquery-mockajax` is needed
* [x] determine whether `animation-frame` is needed
* [x] determine whether `Faker` is needed
* [x] remove `mocha`
* [x] determine whether `pretender` is needed
* [x] determine whether `clockpicker-seconds` is needed

**Comment by TheOtherDude** [comment]
👍  to this since I assumed the dependencies were working correctly, and that cost me :(

**Comment by notmessenger** [comment]
JIRA: FROST-612
