### ISSUE TITLE
Demo is showing error in console when selecting an item

### ISSUE THREAD

**Issue by jscharf** [ciena-frost/ember-frost-object-browser#150]
The following error can be seen in the console when selecting an item in the demo application:
```
Error: There is no route named http://ciena-frost.github.io/#/user/201
```
Once the error has been seen in the console, the user will be unable to select a second item in the list.

**Comment by jscharf** [comment]
Investigation revealed that there is an inconsistency with the version of the `ember-frost-core` package and its usage within the demo application. The version currently in the `package.json` file is 3.1.0 and based on the demo of `frost-link` for this version, it is expecting the `routeNames` property to be an array. 

I propose changing the demo application to use the newer format for `frost-link` in order to resolve this issue.

**Comment by notmessenger** [comment]
This should not be done until after #149 is addressed due to the order of dependency interplay that is being addressed by efforts currently underway.

**Comment by juwara0** [comment]
@jscharf - Did you already verify that updating the demo app to use the new format for `frost-link` resolves the issue?

**Comment by jscharf** [comment]
@juwara0 Yes I have made the changes locally and I no longer see the error when testing the selection/deselection of list items. Note that this does not involve changing any package versions.
