### ISSUE TITLE
Update Documentation for moreActions

### ISSUE THREAD

**Issue by gkchestertron** [ciena-frost/ember-frost-object-browser#163]
Documentation for moreActions in the README and frost-action-bar.js should explain which controls get sliced off and how.

**Comment by lirwin** [comment]
great.  
can you update the `default`s also?  
default for `moreActionsText` is `More...`
default for `moreActions` is initially `true`, then if `true` will automatically be assigned to `Ember.Component[]` if there are more than 4 `frost-button`s in `controls`

clarify `array`s in type column.  array of ??

![screen_shot_2018-01-10_at_1_10_16_pm](https://user-images.githubusercontent.com/4720276/34795698-fc2bc300-f607-11e7-9494-a474fec0a4d2.png)
