### ISSUE TITLE
"TypeError: Cannot read property 'slice' of undefined" in demo app

### ISSUE THREAD

**Issue by notmessenger** [ciena-frost/ember-frost-object-browser#168]
In the client side control flow tab when we click on an item to expand it we have the following issue:
`TypeError: Cannot read property 'slice' of undefined`

**Comment by gkchestertron** [comment]
This looks like it is coming from ember-frost-list: https://github.com/ciena-frost/ember-frost-list/blob/master/addon/components/frost-list.js#L309 - the version of which was recently updated (11-15-2017). So, either an issue with that repo, or our use of it here.

**Comment by notmessenger** [comment]
Has been resolved at some point
