### ISSUE TITLE
dropdown select doesn't clear when use more than once

### ISSUE THREAD

**Issue by pbosse** [ciena-frost/ember-frost-object-browser#50]
To reproduce simply use the dropdown to select a filter.
Click the clear.
The value is cleared
Use the dropdown again and select a filter
Click the clear
The value is not cleared.

Note that the proper event is fired, so that if you une the onFilter, you do receive the event

**Comment by sglanzer** [comment]
This belongs under `ember-frost-core` - moving the issue
