### ISSUE TITLE
Provide block-slot for sort

### ISSUE THREAD

**Issue by pbosse** [ciena-frost/ember-frost-object-browser#52]
Provide a block-slot so that sorting can be implemented but the consumer of ember-frost-object-browser.

**Comment by juwara0** [comment]
@pbosse - Sorting will need to be included in the component that is passed into the view slot:

```
{{#block-slot slot 'view' as |onSelect selections|}}
   {{frost-list...}}
{{/block-slot}}
```

**Comment by sglanzer** [comment]
As @juwara0 mentioned, the intention is that the view layer will contain both the view and controls.  We're going to work on a `frost-list` update to include a controls layer, but in the interim you can refer to https://github.com/ciena-frost/ember-frost-object-browser/tree/master/tests/dummy/app/pods/demo/content-view for an example to follow

**Comment by pbosse** [comment]
Thanks that'll be perfect!
