### ISSUE TITLE
Inline version will always be needed

### ISSUE THREAD

**Issue by TheAxeMan301** [ciena-frost/ember-frost-object-browser#55]
If the inline version of object-browser is removed, several app developers including myself are just going to copy the template and component.js from the last version and maintain it ourselves. Separately. This seems a little inefficient. For this reason I am questioning the current plan. 

There should always be an inline version. It should be possible to make it a more fleshed-out instance of the block-slots version. 

To be honest I currently subclass the inline version and override the template with my own. It's easier than figuring out the block-slots and I get all of the actions and widgets that the inline version sets up for me with the ability to customize as much as I need to. Has anyone done a user count as to who is using block slots vs inline and what their plans for the inline deprecation will be?

**Comment by sglanzer** [comment]
I disagree with this statement.

The inline version 
1. Does not support even a fraction of the Bunsen feature set for facets
2. Does not support customization of the info bar details or actions
3. Does not support infinite scroll
4. Does not support selection action links
5. Does not support inline list item expansion

The list could go on.  All of these are necessary to match the specced object browser pattern and will be provided via other components or yielded contextual components.

Attempting to support this in an inline version would cause an explosion in the required interface and would result in a maintenance nightmare.

The inline version will be deprecated as planned.

**Comment by TheAxeMan301** [comment]
You have not answered the issue I raised. Shouldn't it be possible integrate all these changes into an inline version? As an app developer I want object browser to be a well packaged piece I can easily drop in. The current block slot version does not accomplish this; a large amount of important code has been stripped out. I didn't say that the inline version always needs to be backward compatible or really simple, it just has to be easier than the block slots version.

**Comment by sglanzer** [comment]
Technically yes, but inline would be acting as a proxy layer to all the components underneath and any shift to those component interfaces would require another publish of the inline component.  If you explore the block-slots version of the object browser further I think you'll start to see what I'm referring to.  The interface expands a minor amount but unlocks a huge number of features by not acting as a proxy.

**Comment by TheAxeMan301** [comment]
>  inline would be acting as a proxy layer to all the components underneath and any shift to those     component interfaces would require another publish of the inline component

I agree completely. What I am getting at is that if you don't do that then I have to do it within my app. So does everyone else using object-browser. But if you maintain it in this central repo then everyone can use the same simplified component, saving work for app developers and the team as a whole.

**Comment by sglanzer** [comment]
Seems like a longer discussion that might benefit from a call, we can set something up for next week
