### ISSUE TITLE
support showing number of selected items in action bar

### ISSUE THREAD

**Issue by rox163** [ciena-frost/ember-frost-object-browser#56]
![pasted image at 2016_06_14 11_27 am](https://cloud.githubusercontent.com/assets/313318/16048850/910d6910-3223-11e6-9767-40306b6ce0ce.png)

**Comment by sglanzer** [comment]
I'm asking UX for a definitive view of the object browser pattern, we'll hold off on this until we have confirmation.

**Comment by rox163** [comment]
![pasted image at 2016_06_17 10_07 am](https://cloud.githubusercontent.com/assets/313318/16155010/6551f138-347b-11e6-95b8-684589a2f9fd.png)
