### ISSUE TITLE
DEPRECATION: Overriding Date.parse with Ember.Date.parse is deprecated.

### ISSUE THREAD

**Issue by juwara0** [ciena-frost/ember-frost-object-browser#80]
Upon `ember-serve` of version v16.0.1 of the object-browser a deprecation message is being displayed in the console.

```
DEPRECATION: Overriding Date.parse with Ember.Date.parse is deprecated. Please set ENV.EmberENV.EXTEND_PROTOTYPES.Date to false in config/environment.js


// config/environment.js
ENV = {
  EmberENV: {
    EXTEND_PROTOTYPES: {
      Date: false,
    }
  }
}
 [deprecation id: ds.date.parse-deprecate]
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:21449:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:21357:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:21449:7)
        at invoke (http://localhost:4200/assets/vendor.js:21465:7)
        at deprecate (http://localhost:4200/assets/vendor.js:21418:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:31457:37)
        at deprecate (http://localhost:4200/assets/vendor.js:160753:40)
        at Module.callback (http://localhost:4200/assets/vendor.js:160874:42)
        at Module.exports (http://localhost:4200/assets/vendor.js:131:32)
```

The recommendation in the message above is to set the `Date: false` in the EXTEND_PROTYPES object in the configuration file.

An alternate approach would be to install `ember-disable-prototype-extensions`. 

Both approaches remove the deprecation message but I am leaning toward installing `ember-disable-prototype-extension` as the preferred solution since it is recommended that add-on's be developed with extensions disabled by rwjblue in this issue: https://github.com/ember-cli/ember-cli/issues/3708

**Comment by juwara0** [comment]
@sglanzer - What are your thoughts on this?

**Comment by sglanzer** [comment]
It's recommended, but it's likely to cause us some short term pain - where do we use Date anyway?

**Comment by sglanzer** [comment]
It's solvable- just annoying - I'd rather attack the date directly right now

**Comment by juwara0** [comment]
I have tracked down that ember-data [2.7.0](https://github.com/emberjs/data/blob/master/CHANGELOG.md#release-270-july-25-2016) introduced this deprecation notice in [#4396 Deprecate date parse](https://github.com/emberjs/data/pull/4396/). We were seeing the deprecation notice because we were picking up ember-data 2.7.0 via:https://github.com/ciena-frost/ember-frost-object-browser/blob/7c4766da8444bf3fc2903f6ba101c4d10a5543b2/package.json#L51

I have modified the ember-data version to float on the minor: https://github.com/ciena-frost/ember-frost-object-browser/pull/81

I have not determined what is causing the deprecation notice to show. I have searched through the following looking for a call to `Ember.Date.parse` but have not found one yet:

- ember-frost-object-browser
- ember-frost-bunsen 
- ember-cli-moment-shim
- ember-moment
- ember-data
- ember
