### ISSUE TITLE
Height of the elements is cut in Safari

### ISSUE THREAD

**Issue by vesper2000** [ciena-frost/ember-frost-object-browser#85]
Chrome properly displays  the object browser elements, however in Safari, the elements are cut and squished.

Chrome Demo App:
![screen shot 2016-08-31 at 1 59 54 pm](https://cloud.githubusercontent.com/assets/15364299/18140371/3b5e604e-6f83-11e6-8c6d-c49661ca5149.png)

Safari Demo App:
![screen shot 2016-08-31 at 1 59 15 pm](https://cloud.githubusercontent.com/assets/15364299/18140355/29d95478-6f83-11e6-9ec8-9385445b78a3.png)

**Comment by notmessenger** [comment]
Was closed because we only currently support Chrome and Firefox.
